### PR TITLE
Add package.json for npm/yarn

### PR DESCRIPTION
**Pull request by buu700**
After cycling through the obvious variations of "konami" and "konami code", I found konami-code.js available as a pretty decent option.

### CODE REVIEW

**Comment by georgemandis** [comment]
Ha! I was just perusing the available options too. I like your suggestion. I'll merge and get that up and running shortly...

**Comment by buu700** [comment]
Awesome. I'd already published it, so I just went ahead and added you as a collaborator and removed myself.

**Comment by georgemandis** [comment]
You're one step ahead! I was trying to figure out why it said there was already a published version, so I just bumped the version number slightly.

Thanks for the pull request.

**Comment by buu700** [comment]
lol. Just didn't want to risk someone seeing this before you did and snatching up the name.

**Pull request merged**
