### PR TITLE
added coffeescript file

### PR DESCRIPTION
**Pull request by camray**
Hope you don't mind. I wanted a coffeescript version of this, so I went ahead and converted it.

### CODE REVIEW

**Comment by georgemandis** [comment]
I think that's really cool, but I'm inclined to leave the current repository as it is. I'd have no reservations with you cloning the repo and calling it something like konami-js-coffeescript if you wanted. Thanks though!

**Comment by sukima** [comment]
How about a link in the README to the coffeescript fork?

**Comment by camray** [comment]
If you are inclined to include a link to the fork in the readme it's here: https://github.com/camray/konami-coffee

**Comment by georgemandis** [comment]
Sure thing!

**Pull request closed without merging**
