### PR TITLE
Make this RequireJS compatible.

### PR DESCRIPTION
**Pull request by remybach**

### CODE REVIEW

**Comment by remybach** [comment]
Thanks to @jackfranklin [for the help](https://gist.github.com/4585929/#comment-740511) on this.

**Comment by jackfranklin** [comment]
I would change the conditional to:

`typeof define === "function"`

Rather than just checking for `define`.

**Comment by remybach** [comment]
Fair point... updating now.

**Comment by georgemandis** [comment]
Nice work, however in light of some other pull requests and attention I've decided to streamline the repo and not bake-in and specific module support.  I'd strongly encourage you to fork the repo and implement this there. 

Thanks,
George

**Pull request closed without merging**
