### PR TITLE
Beautified the code

### PR DESCRIPTION
**Pull request by phy25**
Converted spaces to tabs, and fixed the indentation.

### CODE REVIEW

**Comment by sukima** [comment]
Oh cool! I thought about doing this. :+1:

**Comment by georgemandis** [comment]
Thanks! Would you mind redoing it with the latest commit that removes "enter" entirely? I'll merge it then.

**Comment by phy25** [comment]
Done it.

**Comment by abritinthebay** [comment]
You'll need to remove one of the Taps too (A, B, Start is Tap, Tap, Tap in the iPhone... should be Tap, Tap).

**Comment by sukima** [comment]
@abritinthebay and @phy25, you two realize that PR #10 already did this?

**Comment by phy25** [comment]
@sukima I have seen it before so I added commits to change the pattern to fit the latest code... Now should I make another patch?

**Comment by phy25** [comment]
OK another patch is ready: #12.

**Comment by georgemandis** [comment]
Pulled in request #12 - thanks!

**Pull request closed without merging**
