### PR TITLE
Added babel build and eslint file

### PR DESCRIPTION
**Pull request by DavideCarvalho**
So, I've added .babelrc and .eslint files to the project.
I changed konami.js from the root to a folder called "src" and the builded file is at "lib". node_modules and lib folder is git ignored.
eslint is added and added document and window as globals so linter stops saying that they aren't defined.
I edited some easy parts of the code, so the linter stops complaining.

### CODE REVIEW

**Comment by DavideCarvalho** [comment]
referencing #45 
Should create a issue to babel, maybe use #47 ?

**Comment by DavideCarvalho** [comment]
I've send this PR so you can code review it and see if you want something different.

**Comment by georgemandis** [comment]
I'm getting sha integrity errors when I run `npm install` on this. It looks like your'e running Nexus Repository? I don't know much about Nexus, to be honest, but I noticed some of the URLs in `package-lock.json` look like this, which is the source of the issue:

http://nexus.produbanbr.corp/repository/npm-all/@babel/code-frame/-/code-frame-7.0.0.tgz

I deleted the file and ran `npm install` to generate a new `package-lock.json` and it worked fine.

Can you fix this and resubmit? And maybe knockout #46 while you're there since that's a fairly easy one :)

I'm going to merge all this work into the 2.0 branch while we're working on it.

**Comment by DavideCarvalho** [comment]
Sorry, i did this change using my work machine, I forgot to remove the npm registry we use in here.
I commited the remove of package-lock

**Comment by DavideCarvalho** [comment]
Removed bower.json as well
It should close #46

**Comment by georgemandis** [comment]
I pulled your changes into the 2.0 branch I’ve been working on, so I’m going to close this for now.

**Pull request closed without merging**
