### PR TITLE
Ensure invalid swipes and taps restart touch mode captures

### PR DESCRIPTION
**Pull request by BenBergman**
This is a PR to address GH-30. It has been tested in a UIWebView on an iPad Mini.

### CODE REVIEW

**Review by georgemandis — APPROVED** [review]
I dig it.

**Comment by BoldBigflank** [comment]
Can we get a version increment so our bower installs have the latest please?

**Comment by BoldBigflank** [comment]
I mean, a new release/tag for bower to find

**Comment by georgemandis** [comment]
Absolutely!  If you made it a pull request bumping package.json and bower.json to 1.4.8 and the version # and date in the header of konami.js I'd accept it in a heartbeat,  Otherwise I'll find time this weekend :)

**Comment by georgemandis** [comment]
Sorry — strike what I said. I realize I didn't tag the latest update. That's what you were asking :)

I'll get it fixed.

**Comment by georgemandis** [comment]
Should be updated now!

**Pull request merged**
